name: PR was merged
on:
  pull_request:
    types:
      - closed
    branches:
      - main
env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
jobs:
  create_pr:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR was merged"
      - run: echo '${{ toJson(github) }}'
